
name: Add Environment to New Repositories
on:
  repository_dispatch:
    types: [created]

jobs:
  add-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Environment
        run: |
          # Retrieve repository name
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          # Set environment name
          ENVIRONMENT_NAME="production"
          # Create environment
          echo "Creating environment '$ENVIRONMENT_NAME' for repository '$REPO_NAME'..."
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/environments" \
            -d "{
                  \"name\": \"$ENVIRONMENT_NAME\",
                  \"wait_timer\": 10
                }"
          echo "Environment created successfully."
